/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.Export;
	
import nc.vo.pub.*;
import nc.vo.pub.lang.*;
	
/**
 * <b> 分布式数据抽取记录主表VO </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:2016-08-17 10:10:34
 * @author 
 * @version NCPrj 1.0
 */
@SuppressWarnings("serial")
public class FbsDatafileVO extends SuperVO {
	private String groupdef8;
	private String groupdef9;
	private String groupdef6;
	private String groupdef7;
	private String pk_billtype;
	private String operator;
	private String ts;
	private UFDate drevisedate;
	private String vapproveid;
	private UFDate doperatordate;
	private String vapprovenote;
	private UFBoolean isall;
	private String pk_corp;
	private String vrevisorid;
	private String vbillno;
	private Integer dr;
	private String groupdef1;
	private String groupdef20;
	private String pk_busitype;
	private String groupdef5;
	private String groupdef4;
	private String groupdef3;
	private String groupdef2;
	private String voperatorid;
	private String pk_fbs_datafile;
	private Integer vbillstatus;
	private UFDateTime operate_time;
	private UFDateTime start_date;
	private UFDateTime end_date;
	private String vmemo;
	private String groupdef19;
	private String groupdef18;
	private String groupdef17;
	private String groupdef16;
	private String groupdef15;
	private String groupdef14;
	private String groupdef13;
	private String groupdef12;
	private String groupdef11;
	private String groupdef10;
	private UFBoolean isspike;
	private UFBoolean issuccess;
	private UFDate dapprovedate;

	/**
	 * 属性groupdef8的Getter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @return String
	 */
	public String getGroupdef8 () {
		return groupdef8;
	}   
	/**
	 * 属性groupdef8的Setter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @param newGroupdef8 String
	 */
	public void setGroupdef8 (String newGroupdef8 ) {
	 	this.groupdef8 = newGroupdef8;
	} 	  
	/**
	 * 属性groupdef9的Getter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @return String
	 */
	public String getGroupdef9 () {
		return groupdef9;
	}   
	/**
	 * 属性groupdef9的Setter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @param newGroupdef9 String
	 */
	public void setGroupdef9 (String newGroupdef9 ) {
	 	this.groupdef9 = newGroupdef9;
	} 	  
	/**
	 * 属性groupdef6的Getter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @return String
	 */
	public String getGroupdef6 () {
		return groupdef6;
	}   
	/**
	 * 属性groupdef6的Setter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @param newGroupdef6 String
	 */
	public void setGroupdef6 (String newGroupdef6 ) {
	 	this.groupdef6 = newGroupdef6;
	} 	  
	/**
	 * 属性groupdef7的Getter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @return String
	 */
	public String getGroupdef7 () {
		return groupdef7;
	}   
	/**
	 * 属性groupdef7的Setter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @param newGroupdef7 String
	 */
	public void setGroupdef7 (String newGroupdef7 ) {
	 	this.groupdef7 = newGroupdef7;
	} 	  
	/**
	 * 属性pk_billtype的Getter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @return String
	 */
	public String getPk_billtype () {
		return pk_billtype;
	}   
	/**
	 * 属性pk_billtype的Setter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @param newPk_billtype String
	 */
	public void setPk_billtype (String newPk_billtype ) {
	 	this.pk_billtype = newPk_billtype;
	} 	  
	/**
	 * 属性operator的Getter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @return String
	 */
	public String getOperator () {
		return operator;
	}   
	/**
	 * 属性operator的Setter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @param newOperator String
	 */
	public void setOperator (String newOperator ) {
	 	this.operator = newOperator;
	} 	  
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @return String
	 */
	public String getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @param newTs String
	 */
	public void setTs (String newTs ) {
	 	this.ts = newTs;
	} 	  
	/**
	 * 属性drevisedate的Getter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @return UFDate
	 */
	public UFDate getDrevisedate () {
		return drevisedate;
	}   
	/**
	 * 属性drevisedate的Setter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @param newDrevisedate UFDate
	 */
	public void setDrevisedate (UFDate newDrevisedate ) {
	 	this.drevisedate = newDrevisedate;
	} 	  
	/**
	 * 属性vapproveid的Getter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @return String
	 */
	public String getVapproveid () {
		return vapproveid;
	}   
	/**
	 * 属性vapproveid的Setter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @param newVapproveid String
	 */
	public void setVapproveid (String newVapproveid ) {
	 	this.vapproveid = newVapproveid;
	} 	  
	/**
	 * 属性doperatordate的Getter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @return UFDate
	 */
	public UFDate getDoperatordate () {
		return doperatordate;
	}   
	/**
	 * 属性doperatordate的Setter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @param newDoperatordate UFDate
	 */
	public void setDoperatordate (UFDate newDoperatordate ) {
	 	this.doperatordate = newDoperatordate;
	} 	  
	/**
	 * 属性vapprovenote的Getter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @return String
	 */
	public String getVapprovenote () {
		return vapprovenote;
	}   
	/**
	 * 属性vapprovenote的Setter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @param newVapprovenote String
	 */
	public void setVapprovenote (String newVapprovenote ) {
	 	this.vapprovenote = newVapprovenote;
	} 	  
	/**
	 * 属性isall的Getter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @return UFBoolean
	 */
	public UFBoolean getIsall () {
		return isall;
	}   
	/**
	 * 属性isall的Setter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @param newIsall UFBoolean
	 */
	public void setIsall (UFBoolean newIsall ) {
	 	this.isall = newIsall;
	} 	  
	/**
	 * 属性pk_corp的Getter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @return String
	 */
	public String getPk_corp () {
		return pk_corp;
	}   
	/**
	 * 属性pk_corp的Setter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @param newPk_corp String
	 */
	public void setPk_corp (String newPk_corp ) {
	 	this.pk_corp = newPk_corp;
	} 	  
	/**
	 * 属性vrevisorid的Getter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @return String
	 */
	public String getVrevisorid () {
		return vrevisorid;
	}   
	/**
	 * 属性vrevisorid的Setter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @param newVrevisorid String
	 */
	public void setVrevisorid (String newVrevisorid ) {
	 	this.vrevisorid = newVrevisorid;
	} 	  
	/**
	 * 属性vbillno的Getter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @return String
	 */
	public String getVbillno () {
		return vbillno;
	}   
	/**
	 * 属性vbillno的Setter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @param newVbillno String
	 */
	public void setVbillno (String newVbillno ) {
	 	this.vbillno = newVbillno;
	} 	  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @return Integer
	 */
	public Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @param newDr Integer
	 */
	public void setDr (Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性groupdef1的Getter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @return String
	 */
	public String getGroupdef1 () {
		return groupdef1;
	}   
	/**
	 * 属性groupdef1的Setter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @param newGroupdef1 String
	 */
	public void setGroupdef1 (String newGroupdef1 ) {
	 	this.groupdef1 = newGroupdef1;
	} 	  
	/**
	 * 属性groupdef20的Getter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @return String
	 */
	public String getGroupdef20 () {
		return groupdef20;
	}   
	/**
	 * 属性groupdef20的Setter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @param newGroupdef20 String
	 */
	public void setGroupdef20 (String newGroupdef20 ) {
	 	this.groupdef20 = newGroupdef20;
	} 	  
	/**
	 * 属性pk_busitype的Getter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @return String
	 */
	public String getPk_busitype () {
		return pk_busitype;
	}   
	/**
	 * 属性pk_busitype的Setter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @param newPk_busitype String
	 */
	public void setPk_busitype (String newPk_busitype ) {
	 	this.pk_busitype = newPk_busitype;
	} 	  
	/**
	 * 属性groupdef5的Getter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @return String
	 */
	public String getGroupdef5 () {
		return groupdef5;
	}   
	/**
	 * 属性groupdef5的Setter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @param newGroupdef5 String
	 */
	public void setGroupdef5 (String newGroupdef5 ) {
	 	this.groupdef5 = newGroupdef5;
	} 	  
	/**
	 * 属性groupdef4的Getter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @return String
	 */
	public String getGroupdef4 () {
		return groupdef4;
	}   
	/**
	 * 属性groupdef4的Setter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @param newGroupdef4 String
	 */
	public void setGroupdef4 (String newGroupdef4 ) {
	 	this.groupdef4 = newGroupdef4;
	} 	  
	/**
	 * 属性groupdef3的Getter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @return String
	 */
	public String getGroupdef3 () {
		return groupdef3;
	}   
	/**
	 * 属性groupdef3的Setter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @param newGroupdef3 String
	 */
	public void setGroupdef3 (String newGroupdef3 ) {
	 	this.groupdef3 = newGroupdef3;
	} 	  
	/**
	 * 属性groupdef2的Getter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @return String
	 */
	public String getGroupdef2 () {
		return groupdef2;
	}   
	/**
	 * 属性groupdef2的Setter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @param newGroupdef2 String
	 */
	public void setGroupdef2 (String newGroupdef2 ) {
	 	this.groupdef2 = newGroupdef2;
	} 	  
	/**
	 * 属性voperatorid的Getter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @return String
	 */
	public String getVoperatorid () {
		return voperatorid;
	}   
	/**
	 * 属性voperatorid的Setter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @param newVoperatorid String
	 */
	public void setVoperatorid (String newVoperatorid ) {
	 	this.voperatorid = newVoperatorid;
	} 	  
	/**
	 * 属性pk_fbs_datafile的Getter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @return String
	 */
	public String getPk_fbs_datafile () {
		return pk_fbs_datafile;
	}   
	/**
	 * 属性pk_fbs_datafile的Setter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @param newPk_fbs_datafile String
	 */
	public void setPk_fbs_datafile (String newPk_fbs_datafile ) {
	 	this.pk_fbs_datafile = newPk_fbs_datafile;
	} 	  
	/**
	 * 属性vbillstatus的Getter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @return Integer
	 */
	public Integer getVbillstatus () {
		return vbillstatus;
	}   
	/**
	 * 属性vbillstatus的Setter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @param newVbillstatus Integer
	 */
	public void setVbillstatus (Integer newVbillstatus ) {
	 	this.vbillstatus = newVbillstatus;
	} 	  
	/**
	 * 属性operate_time的Getter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @return UFDateTime
	 */
	public UFDateTime getOperate_time () {
		return operate_time;
	}   
	/**
	 * 属性operate_time的Setter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @param newOperate_time UFDateTime
	 */
	public void setOperate_time (UFDateTime newOperate_time ) {
	 	this.operate_time = newOperate_time;
	} 	  
	/**
	 * 属性vmemo的Getter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @return String
	 */
	public String getVmemo () {
		return vmemo;
	}   
	/**
	 * 属性vmemo的Setter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @param newVmemo String
	 */
	public void setVmemo (String newVmemo ) {
	 	this.vmemo = newVmemo;
	} 	  
	/**
	 * 属性groupdef19的Getter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @return String
	 */
	public String getGroupdef19 () {
		return groupdef19;
	}   
	/**
	 * 属性groupdef19的Setter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @param newGroupdef19 String
	 */
	public void setGroupdef19 (String newGroupdef19 ) {
	 	this.groupdef19 = newGroupdef19;
	} 	  
	/**
	 * 属性groupdef18的Getter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @return String
	 */
	public String getGroupdef18 () {
		return groupdef18;
	}   
	/**
	 * 属性groupdef18的Setter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @param newGroupdef18 String
	 */
	public void setGroupdef18 (String newGroupdef18 ) {
	 	this.groupdef18 = newGroupdef18;
	} 	  
	/**
	 * 属性groupdef17的Getter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @return String
	 */
	public String getGroupdef17 () {
		return groupdef17;
	}   
	/**
	 * 属性groupdef17的Setter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @param newGroupdef17 String
	 */
	public void setGroupdef17 (String newGroupdef17 ) {
	 	this.groupdef17 = newGroupdef17;
	} 	  
	/**
	 * 属性groupdef16的Getter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @return String
	 */
	public String getGroupdef16 () {
		return groupdef16;
	}   
	/**
	 * 属性groupdef16的Setter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @param newGroupdef16 String
	 */
	public void setGroupdef16 (String newGroupdef16 ) {
	 	this.groupdef16 = newGroupdef16;
	} 	  
	/**
	 * 属性groupdef15的Getter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @return String
	 */
	public String getGroupdef15 () {
		return groupdef15;
	}   
	/**
	 * 属性groupdef15的Setter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @param newGroupdef15 String
	 */
	public void setGroupdef15 (String newGroupdef15 ) {
	 	this.groupdef15 = newGroupdef15;
	} 	  
	/**
	 * 属性groupdef14的Getter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @return String
	 */
	public String getGroupdef14 () {
		return groupdef14;
	}   
	/**
	 * 属性groupdef14的Setter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @param newGroupdef14 String
	 */
	public void setGroupdef14 (String newGroupdef14 ) {
	 	this.groupdef14 = newGroupdef14;
	} 	  
	/**
	 * 属性groupdef13的Getter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @return String
	 */
	public String getGroupdef13 () {
		return groupdef13;
	}   
	/**
	 * 属性groupdef13的Setter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @param newGroupdef13 String
	 */
	public void setGroupdef13 (String newGroupdef13 ) {
	 	this.groupdef13 = newGroupdef13;
	} 	  
	/**
	 * 属性groupdef12的Getter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @return String
	 */
	public String getGroupdef12 () {
		return groupdef12;
	}   
	/**
	 * 属性groupdef12的Setter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @param newGroupdef12 String
	 */
	public void setGroupdef12 (String newGroupdef12 ) {
	 	this.groupdef12 = newGroupdef12;
	} 	  
	/**
	 * 属性groupdef11的Getter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @return String
	 */
	public String getGroupdef11 () {
		return groupdef11;
	}   
	/**
	 * 属性groupdef11的Setter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @param newGroupdef11 String
	 */
	public void setGroupdef11 (String newGroupdef11 ) {
	 	this.groupdef11 = newGroupdef11;
	} 	  
	/**
	 * 属性groupdef10的Getter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @return String
	 */
	public String getGroupdef10 () {
		return groupdef10;
	}   
	/**
	 * 属性groupdef10的Setter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @param newGroupdef10 String
	 */
	public void setGroupdef10 (String newGroupdef10 ) {
	 	this.groupdef10 = newGroupdef10;
	} 	  
	/**
	 * 属性isspike的Getter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @return UFBoolean
	 */
	public UFBoolean getIsspike () {
		return isspike;
	}   
	/**
	 * 属性isspike的Setter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @param newIsspike UFBoolean
	 */
	public void setIsspike (UFBoolean newIsspike ) {
	 	this.isspike = newIsspike;
	} 	  
	/**
	 * 属性issuccess的Getter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @return UFBoolean
	 */
	public UFBoolean getIssuccess () {
		return issuccess;
	}   
	/**
	 * 属性issuccess的Setter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @param newIssuccess UFBoolean
	 */
	public void setIssuccess (UFBoolean newIssuccess ) {
	 	this.issuccess = newIssuccess;
	} 	  
	/**
	 * 属性dapprovedate的Getter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @return UFDate
	 */
	public UFDate getDapprovedate () {
		return dapprovedate;
	}   
	/**
	 * 属性dapprovedate的Setter方法.
	 * 创建日期:2016-08-17 10:10:34
	 * @param newDapprovedate UFDate
	 */
	public void setDapprovedate (UFDate newDapprovedate ) {
	 	this.dapprovedate = newDapprovedate;
	} 	  
 
	public UFDateTime getStart_date()
	{
		return start_date;
	}
	public void setStart_date(UFDateTime start_date)
	{
		this.start_date = start_date;
	}
	public UFDateTime getEnd_date()
	{
		return end_date;
	}
	public void setEnd_date(UFDateTime end_date)
	{
		this.end_date = end_date;
	}
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2016-08-17 10:10:34
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2016-08-17 10:10:34
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_fbs_datafile";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:2016-08-17 10:10:34
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "fbs_datafile";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2016-08-17 10:10:34
	  */
     public FbsDatafileVO() {
		super();	
	}    
} 
