/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.Export.conf;
	
import nc.vo.pub.*;
import nc.vo.pub.lang.*;
	
/**
 * <b> 数据抽取配置（按照公司配置） </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:2016-11-11 14:23:55
 * @author 王凯强
 * @version NCPrj 1.0
 */
@SuppressWarnings("serial")
public class Fbs_expcorp_confVO extends SuperVO {
	/**
	 * @Field: pk_corp
	 * @Discription: 公司
	 */
	private String pk_corp;
	private UFDateTime ts;
	private String groupdef14;
	private String groupdef19;
	private String groupdef6;
	/**
	 * @Field: exp_flag
	 * @Discription: 导出标记
	 */
	private UFBoolean exp_flag;
	private String groupdef5;
	private String groupdef13;
	private String groupdef7;
	private String groupdef12;
	private String groupdef11;
	private String groupdef18;
	private String groupdef8;
	private String groupdef3;
	private String groupdef10;
	private String groupdef9;
	private String groupdef20;
	private String groupdef15;
	private String groupdef2;
	private String vmemo;
	/**
	 * @Field: exp_pk_corp
	 * @Discription: 导出公司主键
	 */
	private String exp_pk_corp;
	private String groupdef1;
	private String groupdef16;
	private Integer dr;
	/**
	 * @Field: pk_expcorp_conf
	 * @Discription: 表主键
	 */
	private String pk_expcorp_conf;
	private String groupdef4;
	private String groupdef17;

	public static final String PK_CORP = "pk_corp";
	public static final String GROUPDEF14 = "groupdef14";
	public static final String GROUPDEF19 = "groupdef19";
	public static final String GROUPDEF6 = "groupdef6";
	public static final String EXP_FLAG = "exp_flag";
	public static final String GROUPDEF5 = "groupdef5";
	public static final String GROUPDEF13 = "groupdef13";
	public static final String GROUPDEF7 = "groupdef7";
	public static final String GROUPDEF12 = "groupdef12";
	public static final String GROUPDEF11 = "groupdef11";
	public static final String GROUPDEF18 = "groupdef18";
	public static final String GROUPDEF8 = "groupdef8";
	public static final String GROUPDEF3 = "groupdef3";
	public static final String GROUPDEF10 = "groupdef10";
	public static final String GROUPDEF9 = "groupdef9";
	public static final String GROUPDEF20 = "groupdef20";
	public static final String GROUPDEF15 = "groupdef15";
	public static final String GROUPDEF2 = "groupdef2";
	public static final String VMEMO = "vmemo";
	public static final String EXP_PK_CORP = "exp_pk_corp";
	public static final String GROUPDEF1 = "groupdef1";
	public static final String GROUPDEF16 = "groupdef16";
	public static final String PK_EXPCORP_CONF = "pk_expcorp_conf";
	public static final String GROUPDEF4 = "groupdef4";
	public static final String GROUPDEF17 = "groupdef17";
			
	/**
	 * 属性pk_corp的Getter方法.
	 * 创建日期:2016-11-11 14:23:55
	 * @return String
	 */
	public String getPk_corp () {
		return pk_corp;
	}   
	/**
	 * 属性pk_corp的Setter方法.
	 * 创建日期:2016-11-11 14:23:55
	 * @param newPk_corp String
	 */
	public void setPk_corp (String newPk_corp ) {
	 	this.pk_corp = newPk_corp;
	} 	  
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:2016-11-11 14:23:55
	 * @return UFDateTime
	 */
	public UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:2016-11-11 14:23:55
	 * @param newTs UFDateTime
	 */
	public void setTs (UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
	/**
	 * 属性groupdef14的Getter方法.
	 * 创建日期:2016-11-11 14:23:55
	 * @return String
	 */
	public String getGroupdef14 () {
		return groupdef14;
	}   
	/**
	 * 属性groupdef14的Setter方法.
	 * 创建日期:2016-11-11 14:23:55
	 * @param newGroupdef14 String
	 */
	public void setGroupdef14 (String newGroupdef14 ) {
	 	this.groupdef14 = newGroupdef14;
	} 	  
	/**
	 * 属性groupdef19的Getter方法.
	 * 创建日期:2016-11-11 14:23:55
	 * @return String
	 */
	public String getGroupdef19 () {
		return groupdef19;
	}   
	/**
	 * 属性groupdef19的Setter方法.
	 * 创建日期:2016-11-11 14:23:55
	 * @param newGroupdef19 String
	 */
	public void setGroupdef19 (String newGroupdef19 ) {
	 	this.groupdef19 = newGroupdef19;
	} 	  
	/**
	 * 属性groupdef6的Getter方法.
	 * 创建日期:2016-11-11 14:23:55
	 * @return String
	 */
	public String getGroupdef6 () {
		return groupdef6;
	}   
	/**
	 * 属性groupdef6的Setter方法.
	 * 创建日期:2016-11-11 14:23:55
	 * @param newGroupdef6 String
	 */
	public void setGroupdef6 (String newGroupdef6 ) {
	 	this.groupdef6 = newGroupdef6;
	} 	  
	/**
	 * 属性exp_flag的Getter方法.
	 * 创建日期:2016-11-11 14:23:55
	 * @return UFBoolean
	 */
	public UFBoolean getExp_flag () {
		return exp_flag;
	}   
	/**
	 * 属性exp_flag的Setter方法.
	 * 创建日期:2016-11-11 14:23:55
	 * @param newExp_flag UFBoolean
	 */
	public void setExp_flag (UFBoolean newExp_flag ) {
	 	this.exp_flag = newExp_flag;
	} 	  
	/**
	 * 属性groupdef5的Getter方法.
	 * 创建日期:2016-11-11 14:23:55
	 * @return String
	 */
	public String getGroupdef5 () {
		return groupdef5;
	}   
	/**
	 * 属性groupdef5的Setter方法.
	 * 创建日期:2016-11-11 14:23:55
	 * @param newGroupdef5 String
	 */
	public void setGroupdef5 (String newGroupdef5 ) {
	 	this.groupdef5 = newGroupdef5;
	} 	  
	/**
	 * 属性groupdef13的Getter方法.
	 * 创建日期:2016-11-11 14:23:55
	 * @return String
	 */
	public String getGroupdef13 () {
		return groupdef13;
	}   
	/**
	 * 属性groupdef13的Setter方法.
	 * 创建日期:2016-11-11 14:23:55
	 * @param newGroupdef13 String
	 */
	public void setGroupdef13 (String newGroupdef13 ) {
	 	this.groupdef13 = newGroupdef13;
	} 	  
	/**
	 * 属性groupdef7的Getter方法.
	 * 创建日期:2016-11-11 14:23:55
	 * @return String
	 */
	public String getGroupdef7 () {
		return groupdef7;
	}   
	/**
	 * 属性groupdef7的Setter方法.
	 * 创建日期:2016-11-11 14:23:55
	 * @param newGroupdef7 String
	 */
	public void setGroupdef7 (String newGroupdef7 ) {
	 	this.groupdef7 = newGroupdef7;
	} 	  
	/**
	 * 属性groupdef12的Getter方法.
	 * 创建日期:2016-11-11 14:23:55
	 * @return String
	 */
	public String getGroupdef12 () {
		return groupdef12;
	}   
	/**
	 * 属性groupdef12的Setter方法.
	 * 创建日期:2016-11-11 14:23:55
	 * @param newGroupdef12 String
	 */
	public void setGroupdef12 (String newGroupdef12 ) {
	 	this.groupdef12 = newGroupdef12;
	} 	  
	/**
	 * 属性groupdef11的Getter方法.
	 * 创建日期:2016-11-11 14:23:55
	 * @return String
	 */
	public String getGroupdef11 () {
		return groupdef11;
	}   
	/**
	 * 属性groupdef11的Setter方法.
	 * 创建日期:2016-11-11 14:23:55
	 * @param newGroupdef11 String
	 */
	public void setGroupdef11 (String newGroupdef11 ) {
	 	this.groupdef11 = newGroupdef11;
	} 	  
	/**
	 * 属性groupdef18的Getter方法.
	 * 创建日期:2016-11-11 14:23:55
	 * @return String
	 */
	public String getGroupdef18 () {
		return groupdef18;
	}   
	/**
	 * 属性groupdef18的Setter方法.
	 * 创建日期:2016-11-11 14:23:55
	 * @param newGroupdef18 String
	 */
	public void setGroupdef18 (String newGroupdef18 ) {
	 	this.groupdef18 = newGroupdef18;
	} 	  
	/**
	 * 属性groupdef8的Getter方法.
	 * 创建日期:2016-11-11 14:23:55
	 * @return String
	 */
	public String getGroupdef8 () {
		return groupdef8;
	}   
	/**
	 * 属性groupdef8的Setter方法.
	 * 创建日期:2016-11-11 14:23:55
	 * @param newGroupdef8 String
	 */
	public void setGroupdef8 (String newGroupdef8 ) {
	 	this.groupdef8 = newGroupdef8;
	} 	  
	/**
	 * 属性groupdef3的Getter方法.
	 * 创建日期:2016-11-11 14:23:55
	 * @return String
	 */
	public String getGroupdef3 () {
		return groupdef3;
	}   
	/**
	 * 属性groupdef3的Setter方法.
	 * 创建日期:2016-11-11 14:23:55
	 * @param newGroupdef3 String
	 */
	public void setGroupdef3 (String newGroupdef3 ) {
	 	this.groupdef3 = newGroupdef3;
	} 	  
	/**
	 * 属性groupdef10的Getter方法.
	 * 创建日期:2016-11-11 14:23:55
	 * @return String
	 */
	public String getGroupdef10 () {
		return groupdef10;
	}   
	/**
	 * 属性groupdef10的Setter方法.
	 * 创建日期:2016-11-11 14:23:55
	 * @param newGroupdef10 String
	 */
	public void setGroupdef10 (String newGroupdef10 ) {
	 	this.groupdef10 = newGroupdef10;
	} 	  
	/**
	 * 属性groupdef9的Getter方法.
	 * 创建日期:2016-11-11 14:23:55
	 * @return String
	 */
	public String getGroupdef9 () {
		return groupdef9;
	}   
	/**
	 * 属性groupdef9的Setter方法.
	 * 创建日期:2016-11-11 14:23:55
	 * @param newGroupdef9 String
	 */
	public void setGroupdef9 (String newGroupdef9 ) {
	 	this.groupdef9 = newGroupdef9;
	} 	  
	/**
	 * 属性groupdef20的Getter方法.
	 * 创建日期:2016-11-11 14:23:55
	 * @return String
	 */
	public String getGroupdef20 () {
		return groupdef20;
	}   
	/**
	 * 属性groupdef20的Setter方法.
	 * 创建日期:2016-11-11 14:23:55
	 * @param newGroupdef20 String
	 */
	public void setGroupdef20 (String newGroupdef20 ) {
	 	this.groupdef20 = newGroupdef20;
	} 	  
	/**
	 * 属性groupdef15的Getter方法.
	 * 创建日期:2016-11-11 14:23:55
	 * @return String
	 */
	public String getGroupdef15 () {
		return groupdef15;
	}   
	/**
	 * 属性groupdef15的Setter方法.
	 * 创建日期:2016-11-11 14:23:55
	 * @param newGroupdef15 String
	 */
	public void setGroupdef15 (String newGroupdef15 ) {
	 	this.groupdef15 = newGroupdef15;
	} 	  
	/**
	 * 属性groupdef2的Getter方法.
	 * 创建日期:2016-11-11 14:23:55
	 * @return String
	 */
	public String getGroupdef2 () {
		return groupdef2;
	}   
	/**
	 * 属性groupdef2的Setter方法.
	 * 创建日期:2016-11-11 14:23:55
	 * @param newGroupdef2 String
	 */
	public void setGroupdef2 (String newGroupdef2 ) {
	 	this.groupdef2 = newGroupdef2;
	} 	  
	/**
	 * 属性vmemo的Getter方法.
	 * 创建日期:2016-11-11 14:23:55
	 * @return String
	 */
	public String getVmemo () {
		return vmemo;
	}   
	/**
	 * 属性vmemo的Setter方法.
	 * 创建日期:2016-11-11 14:23:55
	 * @param newVmemo String
	 */
	public void setVmemo (String newVmemo ) {
	 	this.vmemo = newVmemo;
	} 	  
	/**
	 * 属性exp_pk_corp的Getter方法.
	 * 创建日期:2016-11-11 14:23:55
	 * @return String
	 */
	public String getExp_pk_corp () {
		return exp_pk_corp;
	}   
	/**
	 * 属性exp_pk_corp的Setter方法.
	 * 创建日期:2016-11-11 14:23:55
	 * @param newExp_pk_corp String
	 */
	public void setExp_pk_corp (String newExp_pk_corp ) {
	 	this.exp_pk_corp = newExp_pk_corp;
	} 	  
	/**
	 * 属性groupdef1的Getter方法.
	 * 创建日期:2016-11-11 14:23:55
	 * @return String
	 */
	public String getGroupdef1 () {
		return groupdef1;
	}   
	/**
	 * 属性groupdef1的Setter方法.
	 * 创建日期:2016-11-11 14:23:55
	 * @param newGroupdef1 String
	 */
	public void setGroupdef1 (String newGroupdef1 ) {
	 	this.groupdef1 = newGroupdef1;
	} 	  
	/**
	 * 属性groupdef16的Getter方法.
	 * 创建日期:2016-11-11 14:23:55
	 * @return String
	 */
	public String getGroupdef16 () {
		return groupdef16;
	}   
	/**
	 * 属性groupdef16的Setter方法.
	 * 创建日期:2016-11-11 14:23:55
	 * @param newGroupdef16 String
	 */
	public void setGroupdef16 (String newGroupdef16 ) {
	 	this.groupdef16 = newGroupdef16;
	} 	  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:2016-11-11 14:23:55
	 * @return Integer
	 */
	public Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:2016-11-11 14:23:55
	 * @param newDr Integer
	 */
	public void setDr (Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性pk_expcorp_conf的Getter方法.
	 * 创建日期:2016-11-11 14:23:55
	 * @return String
	 */
	public String getPk_expcorp_conf () {
		return pk_expcorp_conf;
	}   
	/**
	 * 属性pk_expcorp_conf的Setter方法.
	 * 创建日期:2016-11-11 14:23:55
	 * @param newPk_expcorp_conf String
	 */
	public void setPk_expcorp_conf (String newPk_expcorp_conf ) {
	 	this.pk_expcorp_conf = newPk_expcorp_conf;
	} 	  
	/**
	 * 属性groupdef4的Getter方法.
	 * 创建日期:2016-11-11 14:23:55
	 * @return String
	 */
	public String getGroupdef4 () {
		return groupdef4;
	}   
	/**
	 * 属性groupdef4的Setter方法.
	 * 创建日期:2016-11-11 14:23:55
	 * @param newGroupdef4 String
	 */
	public void setGroupdef4 (String newGroupdef4 ) {
	 	this.groupdef4 = newGroupdef4;
	} 	  
	/**
	 * 属性groupdef17的Getter方法.
	 * 创建日期:2016-11-11 14:23:55
	 * @return String
	 */
	public String getGroupdef17 () {
		return groupdef17;
	}   
	/**
	 * 属性groupdef17的Setter方法.
	 * 创建日期:2016-11-11 14:23:55
	 * @param newGroupdef17 String
	 */
	public void setGroupdef17 (String newGroupdef17 ) {
	 	this.groupdef17 = newGroupdef17;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2016-11-11 14:23:55
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2016-11-11 14:23:55
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_expcorp_conf";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:2016-11-11 14:23:55
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "fbs_expcorp_conf";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2016-11-11 14:23:55
	  */
     public Fbs_expcorp_confVO() {
		super();	
	}    
} 
