/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.djdz;
	
import nc.vo.pub.*;
import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:2016-08-15 12:58:21
 * @author 
 * @version NCPrj 1.0
 */
@SuppressWarnings("serial")
public class DataControl_typeVO extends SuperVO {
	private String pk_corp;
	private String ts;
	private UFDate drevisedate;
	private String vuserdef9;
	private String vuserdef3;
	private String vuserdef11;
	private String vuserdef17;
	private String vuserdef14;
	private String pk_busitype;
	private String vuserdef4;
	private String vapproveid;
	private String vrevisorid;
	private String vapprovenote;
	private String vuserdef1;
	private String vuserdef12;
	private String vuserdef8;
	private String vuserdef13;
	private String vuserdef19;
	private String vuserdef6;
	private String type_code;
	private UFDate dapprovedate;
	private String vuserdef10;
	private String vuserdef18;
	private String pk_datacontrol_type;
	private String vuserdef5;
	private UFDate doperatordate;
	private String vnote;
	private String pk_defdoclist;
	private String vuserdef7;
	private String pk_billtype;
	private Integer vbillstatus;
	private String vuserdef15;
	private String voperatorid;
	private String vuserdef16;
	private String vbillno;
	private String vuserdef20;
	private Integer dr;
	private String vuserdef2;
	private String type_name;

	public static final String PK_CORP = "pk_corp";
	public static final String DREVISEDATE = "drevisedate";
	public static final String VUSERDEF9 = "vuserdef9";
	public static final String VUSERDEF3 = "vuserdef3";
	public static final String VUSERDEF11 = "vuserdef11";
	public static final String VUSERDEF17 = "vuserdef17";
	public static final String VUSERDEF14 = "vuserdef14";
	public static final String PK_BUSITYPE = "pk_busitype";
	public static final String VUSERDEF4 = "vuserdef4";
	public static final String VAPPROVEID = "vapproveid";
	public static final String VREVISORID = "vrevisorid";
	public static final String VAPPROVENOTE = "vapprovenote";
	public static final String VUSERDEF1 = "vuserdef1";
	public static final String VUSERDEF12 = "vuserdef12";
	public static final String VUSERDEF8 = "vuserdef8";
	public static final String VUSERDEF13 = "vuserdef13";
	public static final String VUSERDEF19 = "vuserdef19";
	public static final String VUSERDEF6 = "vuserdef6";
	public static final String TYPE_CODE = "type_code";
	public static final String DAPPROVEDATE = "dapprovedate";
	public static final String VUSERDEF10 = "vuserdef10";
	public static final String VUSERDEF18 = "vuserdef18";
	public static final String PK_DC_DATACONTROL_TYPE = "pk_dc_datacontrol_type";
	public static final String VUSERDEF5 = "vuserdef5";
	public static final String DOPERATORDATE = "doperatordate";
	public static final String VNOTE = "vnote";
	public static final String PK_DEFDOCLIST = "pk_defdoclist";
	public static final String VUSERDEF7 = "vuserdef7";
	public static final String PK_BILLTYPE = "pk_billtype";
	public static final String VBILLSTATUS = "vbillstatus";
	public static final String VUSERDEF15 = "vuserdef15";
	public static final String VOPERATORID = "voperatorid";
	public static final String VUSERDEF16 = "vuserdef16";
	public static final String VBILLNO = "vbillno";
	public static final String VUSERDEF20 = "vuserdef20";
	public static final String VUSERDEF2 = "vuserdef2";
	public static final String TYPE_NAME = "type_name";
			
	/**
	 * 属性pk_corp的Getter方法.
	 * 创建日期:2016-08-15 12:58:21
	 * @return String
	 */
	public String getPk_corp () {
		return pk_corp;
	}   
	/**
	 * 属性pk_corp的Setter方法.
	 * 创建日期:2016-08-15 12:58:21
	 * @param newPk_corp String
	 */
	public void setPk_corp (String newPk_corp ) {
	 	this.pk_corp = newPk_corp;
	} 	  
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:2016-08-15 12:58:21
	 * @return String
	 */
	public String getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:2016-08-15 12:58:21
	 * @param newTs String
	 */
	public void setTs (String newTs ) {
	 	this.ts = newTs;
	} 	  
	/**
	 * 属性drevisedate的Getter方法.
	 * 创建日期:2016-08-15 12:58:21
	 * @return UFDate
	 */
	public UFDate getDrevisedate () {
		return drevisedate;
	}   
	/**
	 * 属性drevisedate的Setter方法.
	 * 创建日期:2016-08-15 12:58:21
	 * @param newDrevisedate UFDate
	 */
	public void setDrevisedate (UFDate newDrevisedate ) {
	 	this.drevisedate = newDrevisedate;
	} 	  
	/**
	 * 属性vuserdef9的Getter方法.
	 * 创建日期:2016-08-15 12:58:21
	 * @return String
	 */
	public String getVuserdef9 () {
		return vuserdef9;
	}   
	/**
	 * 属性vuserdef9的Setter方法.
	 * 创建日期:2016-08-15 12:58:21
	 * @param newVuserdef9 String
	 */
	public void setVuserdef9 (String newVuserdef9 ) {
	 	this.vuserdef9 = newVuserdef9;
	} 	  
	/**
	 * 属性vuserdef3的Getter方法.
	 * 创建日期:2016-08-15 12:58:21
	 * @return String
	 */
	public String getVuserdef3 () {
		return vuserdef3;
	}   
	/**
	 * 属性vuserdef3的Setter方法.
	 * 创建日期:2016-08-15 12:58:21
	 * @param newVuserdef3 String
	 */
	public void setVuserdef3 (String newVuserdef3 ) {
	 	this.vuserdef3 = newVuserdef3;
	} 	  
	/**
	 * 属性vuserdef11的Getter方法.
	 * 创建日期:2016-08-15 12:58:21
	 * @return String
	 */
	public String getVuserdef11 () {
		return vuserdef11;
	}   
	/**
	 * 属性vuserdef11的Setter方法.
	 * 创建日期:2016-08-15 12:58:21
	 * @param newVuserdef11 String
	 */
	public void setVuserdef11 (String newVuserdef11 ) {
	 	this.vuserdef11 = newVuserdef11;
	} 	  
	/**
	 * 属性vuserdef17的Getter方法.
	 * 创建日期:2016-08-15 12:58:21
	 * @return String
	 */
	public String getVuserdef17 () {
		return vuserdef17;
	}   
	/**
	 * 属性vuserdef17的Setter方法.
	 * 创建日期:2016-08-15 12:58:21
	 * @param newVuserdef17 String
	 */
	public void setVuserdef17 (String newVuserdef17 ) {
	 	this.vuserdef17 = newVuserdef17;
	} 	  
	/**
	 * 属性vuserdef14的Getter方法.
	 * 创建日期:2016-08-15 12:58:21
	 * @return String
	 */
	public String getVuserdef14 () {
		return vuserdef14;
	}   
	/**
	 * 属性vuserdef14的Setter方法.
	 * 创建日期:2016-08-15 12:58:21
	 * @param newVuserdef14 String
	 */
	public void setVuserdef14 (String newVuserdef14 ) {
	 	this.vuserdef14 = newVuserdef14;
	} 	  
	/**
	 * 属性pk_busitype的Getter方法.
	 * 创建日期:2016-08-15 12:58:21
	 * @return String
	 */
	public String getPk_busitype () {
		return pk_busitype;
	}   
	/**
	 * 属性pk_busitype的Setter方法.
	 * 创建日期:2016-08-15 12:58:21
	 * @param newPk_busitype String
	 */
	public void setPk_busitype (String newPk_busitype ) {
	 	this.pk_busitype = newPk_busitype;
	} 	  
	/**
	 * 属性vuserdef4的Getter方法.
	 * 创建日期:2016-08-15 12:58:21
	 * @return String
	 */
	public String getVuserdef4 () {
		return vuserdef4;
	}   
	/**
	 * 属性vuserdef4的Setter方法.
	 * 创建日期:2016-08-15 12:58:21
	 * @param newVuserdef4 String
	 */
	public void setVuserdef4 (String newVuserdef4 ) {
	 	this.vuserdef4 = newVuserdef4;
	} 	  
	/**
	 * 属性vapproveid的Getter方法.
	 * 创建日期:2016-08-15 12:58:21
	 * @return String
	 */
	public String getVapproveid () {
		return vapproveid;
	}   
	/**
	 * 属性vapproveid的Setter方法.
	 * 创建日期:2016-08-15 12:58:21
	 * @param newVapproveid String
	 */
	public void setVapproveid (String newVapproveid ) {
	 	this.vapproveid = newVapproveid;
	} 	  
	/**
	 * 属性vrevisorid的Getter方法.
	 * 创建日期:2016-08-15 12:58:21
	 * @return String
	 */
	public String getVrevisorid () {
		return vrevisorid;
	}   
	/**
	 * 属性vrevisorid的Setter方法.
	 * 创建日期:2016-08-15 12:58:21
	 * @param newVrevisorid String
	 */
	public void setVrevisorid (String newVrevisorid ) {
	 	this.vrevisorid = newVrevisorid;
	} 	  
	/**
	 * 属性vapprovenote的Getter方法.
	 * 创建日期:2016-08-15 12:58:21
	 * @return String
	 */
	public String getVapprovenote () {
		return vapprovenote;
	}   
	/**
	 * 属性vapprovenote的Setter方法.
	 * 创建日期:2016-08-15 12:58:21
	 * @param newVapprovenote String
	 */
	public void setVapprovenote (String newVapprovenote ) {
	 	this.vapprovenote = newVapprovenote;
	} 	  
	/**
	 * 属性vuserdef1的Getter方法.
	 * 创建日期:2016-08-15 12:58:21
	 * @return String
	 */
	public String getVuserdef1 () {
		return vuserdef1;
	}   
	/**
	 * 属性vuserdef1的Setter方法.
	 * 创建日期:2016-08-15 12:58:21
	 * @param newVuserdef1 String
	 */
	public void setVuserdef1 (String newVuserdef1 ) {
	 	this.vuserdef1 = newVuserdef1;
	} 	  
	/**
	 * 属性vuserdef12的Getter方法.
	 * 创建日期:2016-08-15 12:58:21
	 * @return String
	 */
	public String getVuserdef12 () {
		return vuserdef12;
	}   
	/**
	 * 属性vuserdef12的Setter方法.
	 * 创建日期:2016-08-15 12:58:21
	 * @param newVuserdef12 String
	 */
	public void setVuserdef12 (String newVuserdef12 ) {
	 	this.vuserdef12 = newVuserdef12;
	} 	  
	/**
	 * 属性vuserdef8的Getter方法.
	 * 创建日期:2016-08-15 12:58:21
	 * @return String
	 */
	public String getVuserdef8 () {
		return vuserdef8;
	}   
	/**
	 * 属性vuserdef8的Setter方法.
	 * 创建日期:2016-08-15 12:58:21
	 * @param newVuserdef8 String
	 */
	public void setVuserdef8 (String newVuserdef8 ) {
	 	this.vuserdef8 = newVuserdef8;
	} 	  
	/**
	 * 属性vuserdef13的Getter方法.
	 * 创建日期:2016-08-15 12:58:21
	 * @return String
	 */
	public String getVuserdef13 () {
		return vuserdef13;
	}   
	/**
	 * 属性vuserdef13的Setter方法.
	 * 创建日期:2016-08-15 12:58:21
	 * @param newVuserdef13 String
	 */
	public void setVuserdef13 (String newVuserdef13 ) {
	 	this.vuserdef13 = newVuserdef13;
	} 	  
	/**
	 * 属性vuserdef19的Getter方法.
	 * 创建日期:2016-08-15 12:58:21
	 * @return String
	 */
	public String getVuserdef19 () {
		return vuserdef19;
	}   
	/**
	 * 属性vuserdef19的Setter方法.
	 * 创建日期:2016-08-15 12:58:21
	 * @param newVuserdef19 String
	 */
	public void setVuserdef19 (String newVuserdef19 ) {
	 	this.vuserdef19 = newVuserdef19;
	} 	  
	/**
	 * 属性vuserdef6的Getter方法.
	 * 创建日期:2016-08-15 12:58:21
	 * @return String
	 */
	public String getVuserdef6 () {
		return vuserdef6;
	}   
	/**
	 * 属性vuserdef6的Setter方法.
	 * 创建日期:2016-08-15 12:58:21
	 * @param newVuserdef6 String
	 */
	public void setVuserdef6 (String newVuserdef6 ) {
	 	this.vuserdef6 = newVuserdef6;
	} 	  
	/**
	 * 属性type_code的Getter方法.
	 * 创建日期:2016-08-15 12:58:21
	 * @return String
	 */
	public String getType_code () {
		return type_code;
	}   
	/**
	 * 属性type_code的Setter方法.
	 * 创建日期:2016-08-15 12:58:21
	 * @param newType_code String
	 */
	public void setType_code (String newType_code ) {
	 	this.type_code = newType_code;
	} 	  
	/**
	 * 属性dapprovedate的Getter方法.
	 * 创建日期:2016-08-15 12:58:21
	 * @return UFDate
	 */
	public UFDate getDapprovedate () {
		return dapprovedate;
	}   
	/**
	 * 属性dapprovedate的Setter方法.
	 * 创建日期:2016-08-15 12:58:21
	 * @param newDapprovedate UFDate
	 */
	public void setDapprovedate (UFDate newDapprovedate ) {
	 	this.dapprovedate = newDapprovedate;
	} 	  
	/**
	 * 属性vuserdef10的Getter方法.
	 * 创建日期:2016-08-15 12:58:21
	 * @return String
	 */
	public String getVuserdef10 () {
		return vuserdef10;
	}   
	/**
	 * 属性vuserdef10的Setter方法.
	 * 创建日期:2016-08-15 12:58:21
	 * @param newVuserdef10 String
	 */
	public void setVuserdef10 (String newVuserdef10 ) {
	 	this.vuserdef10 = newVuserdef10;
	} 	  
	/**
	 * 属性vuserdef18的Getter方法.
	 * 创建日期:2016-08-15 12:58:21
	 * @return String
	 */
	public String getVuserdef18 () {
		return vuserdef18;
	}   
	/**
	 * 属性vuserdef18的Setter方法.
	 * 创建日期:2016-08-15 12:58:21
	 * @param newVuserdef18 String
	 */
	public void setVuserdef18 (String newVuserdef18 ) {
	 	this.vuserdef18 = newVuserdef18;
	} 	  
	/**
	 * 属性pk_dc_datacontrol_type的Getter方法.
	 * 创建日期:2016-08-15 12:58:21
	 * @return String
	 */
	public String getPk_datacontrol_type () {
		return pk_datacontrol_type;
	}   
	/**
	 * 属性pk_dc_datacontrol_type的Setter方法.
	 * 创建日期:2016-08-15 12:58:21
	 * @param newPk_dc_datacontrol_type String
	 */
	public void setPk_datacontrol_type (String newPk_datacontrol_type ) {
	 	this.pk_datacontrol_type = newPk_datacontrol_type;
	} 	  
	/**
	 * 属性vuserdef5的Getter方法.
	 * 创建日期:2016-08-15 12:58:21
	 * @return String
	 */
	public String getVuserdef5 () {
		return vuserdef5;
	}   
	/**
	 * 属性vuserdef5的Setter方法.
	 * 创建日期:2016-08-15 12:58:21
	 * @param newVuserdef5 String
	 */
	public void setVuserdef5 (String newVuserdef5 ) {
	 	this.vuserdef5 = newVuserdef5;
	} 	  
	/**
	 * 属性doperatordate的Getter方法.
	 * 创建日期:2016-08-15 12:58:21
	 * @return UFDate
	 */
	public UFDate getDoperatordate () {
		return doperatordate;
	}   
	/**
	 * 属性doperatordate的Setter方法.
	 * 创建日期:2016-08-15 12:58:21
	 * @param newDoperatordate UFDate
	 */
	public void setDoperatordate (UFDate newDoperatordate ) {
	 	this.doperatordate = newDoperatordate;
	} 	  
	/**
	 * 属性vnote的Getter方法.
	 * 创建日期:2016-08-15 12:58:21
	 * @return String
	 */
	public String getVnote () {
		return vnote;
	}   
	/**
	 * 属性vnote的Setter方法.
	 * 创建日期:2016-08-15 12:58:21
	 * @param newVnote String
	 */
	public void setVnote (String newVnote ) {
	 	this.vnote = newVnote;
	} 	  
	/**
	 * 属性pk_defdoclist的Getter方法.
	 * 创建日期:2016-08-15 12:58:21
	 * @return String
	 */
	public String getPk_defdoclist () {
		return pk_defdoclist;
	}   
	/**
	 * 属性pk_defdoclist的Setter方法.
	 * 创建日期:2016-08-15 12:58:21
	 * @param newPk_defdoclist String
	 */
	public void setPk_defdoclist (String newPk_defdoclist ) {
	 	this.pk_defdoclist = newPk_defdoclist;
	} 	  
	/**
	 * 属性vuserdef7的Getter方法.
	 * 创建日期:2016-08-15 12:58:21
	 * @return String
	 */
	public String getVuserdef7 () {
		return vuserdef7;
	}   
	/**
	 * 属性vuserdef7的Setter方法.
	 * 创建日期:2016-08-15 12:58:21
	 * @param newVuserdef7 String
	 */
	public void setVuserdef7 (String newVuserdef7 ) {
	 	this.vuserdef7 = newVuserdef7;
	} 	  
	/**
	 * 属性pk_billtype的Getter方法.
	 * 创建日期:2016-08-15 12:58:21
	 * @return String
	 */
	public String getPk_billtype () {
		return pk_billtype;
	}   
	/**
	 * 属性pk_billtype的Setter方法.
	 * 创建日期:2016-08-15 12:58:21
	 * @param newPk_billtype String
	 */
	public void setPk_billtype (String newPk_billtype ) {
	 	this.pk_billtype = newPk_billtype;
	} 	  
	/**
	 * 属性vbillstatus的Getter方法.
	 * 创建日期:2016-08-15 12:58:21
	 * @return Integer
	 */
	public Integer getVbillstatus () {
		return vbillstatus;
	}   
	/**
	 * 属性vbillstatus的Setter方法.
	 * 创建日期:2016-08-15 12:58:21
	 * @param newVbillstatus Integer
	 */
	public void setVbillstatus (Integer newVbillstatus ) {
	 	this.vbillstatus = newVbillstatus;
	} 	  
	/**
	 * 属性vuserdef15的Getter方法.
	 * 创建日期:2016-08-15 12:58:21
	 * @return String
	 */
	public String getVuserdef15 () {
		return vuserdef15;
	}   
	/**
	 * 属性vuserdef15的Setter方法.
	 * 创建日期:2016-08-15 12:58:21
	 * @param newVuserdef15 String
	 */
	public void setVuserdef15 (String newVuserdef15 ) {
	 	this.vuserdef15 = newVuserdef15;
	} 	  
	/**
	 * 属性voperatorid的Getter方法.
	 * 创建日期:2016-08-15 12:58:21
	 * @return String
	 */
	public String getVoperatorid () {
		return voperatorid;
	}   
	/**
	 * 属性voperatorid的Setter方法.
	 * 创建日期:2016-08-15 12:58:21
	 * @param newVoperatorid String
	 */
	public void setVoperatorid (String newVoperatorid ) {
	 	this.voperatorid = newVoperatorid;
	} 	  
	/**
	 * 属性vuserdef16的Getter方法.
	 * 创建日期:2016-08-15 12:58:21
	 * @return String
	 */
	public String getVuserdef16 () {
		return vuserdef16;
	}   
	/**
	 * 属性vuserdef16的Setter方法.
	 * 创建日期:2016-08-15 12:58:21
	 * @param newVuserdef16 String
	 */
	public void setVuserdef16 (String newVuserdef16 ) {
	 	this.vuserdef16 = newVuserdef16;
	} 	  
	/**
	 * 属性vbillno的Getter方法.
	 * 创建日期:2016-08-15 12:58:21
	 * @return String
	 */
	public String getVbillno () {
		return vbillno;
	}   
	/**
	 * 属性vbillno的Setter方法.
	 * 创建日期:2016-08-15 12:58:21
	 * @param newVbillno String
	 */
	public void setVbillno (String newVbillno ) {
	 	this.vbillno = newVbillno;
	} 	  
	/**
	 * 属性vuserdef20的Getter方法.
	 * 创建日期:2016-08-15 12:58:21
	 * @return String
	 */
	public String getVuserdef20 () {
		return vuserdef20;
	}   
	/**
	 * 属性vuserdef20的Setter方法.
	 * 创建日期:2016-08-15 12:58:21
	 * @param newVuserdef20 String
	 */
	public void setVuserdef20 (String newVuserdef20 ) {
	 	this.vuserdef20 = newVuserdef20;
	} 	  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:2016-08-15 12:58:21
	 * @return Integer
	 */
	public Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:2016-08-15 12:58:21
	 * @param newDr Integer
	 */
	public void setDr (Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性vuserdef2的Getter方法.
	 * 创建日期:2016-08-15 12:58:21
	 * @return String
	 */
	public String getVuserdef2 () {
		return vuserdef2;
	}   
	/**
	 * 属性vuserdef2的Setter方法.
	 * 创建日期:2016-08-15 12:58:21
	 * @param newVuserdef2 String
	 */
	public void setVuserdef2 (String newVuserdef2 ) {
	 	this.vuserdef2 = newVuserdef2;
	} 	  
	/**
	 * 属性type_name的Getter方法.
	 * 创建日期:2016-08-15 12:58:21
	 * @return String
	 */
	public String getType_name () {
		return type_name;
	}   
	/**
	 * 属性type_name的Setter方法.
	 * 创建日期:2016-08-15 12:58:21
	 * @param newType_name String
	 */
	public void setType_name (String newType_name ) {
	 	this.type_name = newType_name;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2016-08-15 12:58:21
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2016-08-15 12:58:21
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_datacontrol_type";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:2016-08-15 12:58:21
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "dc_datacontrol_type";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2016-08-15 12:58:21
	  */
     public DataControl_typeVO() {
		super();	
	}    
} 
