/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.Export;
	
import nc.vo.pub.*;
import nc.vo.pub.lang.*;
	
/**
 * <b> 分布式数据抽取记录子表VO </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:2016-08-16 17:22:11
 * @author 王凯强
 * @version NCPrj 1.0
 */
@SuppressWarnings("serial")
public class FbsDataFileItemVO extends SuperVO {
	private String vuserdef2;
	private String vuserdef3;
	private String pk_billtype;
	private String vuserdef1;
	private String ts;
	private String vapproveid;
	private UFDate drevisedate;
	private String data_size;
	private UFDate doperatordate;
	private String vapprovenote;
	private String vuserdef11;
	private String vuserdef12;
	private String pk_corp;
	private String vuserdef13;
	private String vrevisorid;
	private String vuserdef14;
	private String vbillno;
	private Integer dr;
	private String vuserdef10;
	private String vuserdef7;
	private String vuserdef19;
	private String vuserdef6;
	private String vuserdef5;
	private String vuserdef4;
	private String pk_busitype;
	private String vuserdef15;
	private String vuserdef16;
	private String vuserdef9;
	private String vuserdef17;
	private String vuserdef8;
	private String vuserdef18;
	private String table_name;
	private String voperatorid;
	private String pk_fbs_datafile;
	private Integer vbillstatus;
	private String pk_fbs_datafile_item;
	private String vuserdef20;
	private String vnote;
	private UFDate dapprovedate;

	public static final String VUSERDEF2 = "vuserdef2";
	public static final String VUSERDEF3 = "vuserdef3";
	public static final String PK_BILLTYPE = "pk_billtype";
	public static final String VUSERDEF1 = "vuserdef1";
	public static final String VAPPROVEID = "vapproveid";
	public static final String DREVISEDATE = "drevisedate";
	public static final String DATA_SIZE = "data_size";
	public static final String DOPERATORDATE = "doperatordate";
	public static final String VAPPROVENOTE = "vapprovenote";
	public static final String VUSERDEF11 = "vuserdef11";
	public static final String VUSERDEF12 = "vuserdef12";
	public static final String PK_CORP = "pk_corp";
	public static final String VUSERDEF13 = "vuserdef13";
	public static final String VREVISORID = "vrevisorid";
	public static final String VUSERDEF14 = "vuserdef14";
	public static final String VBILLNO = "vbillno";
	public static final String VUSERDEF10 = "vuserdef10";
	public static final String VUSERDEF7 = "vuserdef7";
	public static final String VUSERDEF19 = "vuserdef19";
	public static final String VUSERDEF6 = "vuserdef6";
	public static final String VUSERDEF5 = "vuserdef5";
	public static final String VUSERDEF4 = "vuserdef4";
	public static final String PK_BUSITYPE = "pk_busitype";
	public static final String VUSERDEF15 = "vuserdef15";
	public static final String VUSERDEF16 = "vuserdef16";
	public static final String VUSERDEF9 = "vuserdef9";
	public static final String VUSERDEF17 = "vuserdef17";
	public static final String VUSERDEF8 = "vuserdef8";
	public static final String VUSERDEF18 = "vuserdef18";
	public static final String TABLE_NAME = "table_name";
	public static final String VOPERATORID = "voperatorid";
	public static final String PK_FBS_DATAFILE = "pk_fbs_datafile";
	public static final String VBILLSTATUS = "vbillstatus";
	public static final String PK_FBS_DATAFILE_ITEM = "pk_fbs_datafile_item";
	public static final String VUSERDEF20 = "vuserdef20";
	public static final String VNOTE = "vnote";
	public static final String DAPPROVEDATE = "dapprovedate";
			
	/**
	 * 属性vuserdef2的Getter方法.
	 * 创建日期:2016-08-16 17:22:11
	 * @return String
	 */
	public String getVuserdef2 () {
		return vuserdef2;
	}   
	/**
	 * 属性vuserdef2的Setter方法.
	 * 创建日期:2016-08-16 17:22:11
	 * @param newVuserdef2 String
	 */
	public void setVuserdef2 (String newVuserdef2 ) {
	 	this.vuserdef2 = newVuserdef2;
	} 	  
	/**
	 * 属性vuserdef3的Getter方法.
	 * 创建日期:2016-08-16 17:22:11
	 * @return String
	 */
	public String getVuserdef3 () {
		return vuserdef3;
	}   
	/**
	 * 属性vuserdef3的Setter方法.
	 * 创建日期:2016-08-16 17:22:11
	 * @param newVuserdef3 String
	 */
	public void setVuserdef3 (String newVuserdef3 ) {
	 	this.vuserdef3 = newVuserdef3;
	} 	  
	/**
	 * 属性pk_billtype的Getter方法.
	 * 创建日期:2016-08-16 17:22:11
	 * @return String
	 */
	public String getPk_billtype () {
		return pk_billtype;
	}   
	/**
	 * 属性pk_billtype的Setter方法.
	 * 创建日期:2016-08-16 17:22:11
	 * @param newPk_billtype String
	 */
	public void setPk_billtype (String newPk_billtype ) {
	 	this.pk_billtype = newPk_billtype;
	} 	  
	/**
	 * 属性vuserdef1的Getter方法.
	 * 创建日期:2016-08-16 17:22:11
	 * @return String
	 */
	public String getVuserdef1 () {
		return vuserdef1;
	}   
	/**
	 * 属性vuserdef1的Setter方法.
	 * 创建日期:2016-08-16 17:22:11
	 * @param newVuserdef1 String
	 */
	public void setVuserdef1 (String newVuserdef1 ) {
	 	this.vuserdef1 = newVuserdef1;
	} 	  
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:2016-08-16 17:22:11
	 * @return String
	 */
	public String getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:2016-08-16 17:22:11
	 * @param newTs String
	 */
	public void setTs (String newTs ) {
	 	this.ts = newTs;
	} 	  
	/**
	 * 属性vapproveid的Getter方法.
	 * 创建日期:2016-08-16 17:22:11
	 * @return String
	 */
	public String getVapproveid () {
		return vapproveid;
	}   
	/**
	 * 属性vapproveid的Setter方法.
	 * 创建日期:2016-08-16 17:22:11
	 * @param newVapproveid String
	 */
	public void setVapproveid (String newVapproveid ) {
	 	this.vapproveid = newVapproveid;
	} 	  
	/**
	 * 属性drevisedate的Getter方法.
	 * 创建日期:2016-08-16 17:22:11
	 * @return UFDate
	 */
	public UFDate getDrevisedate () {
		return drevisedate;
	}   
	/**
	 * 属性drevisedate的Setter方法.
	 * 创建日期:2016-08-16 17:22:11
	 * @param newDrevisedate UFDate
	 */
	public void setDrevisedate (UFDate newDrevisedate ) {
	 	this.drevisedate = newDrevisedate;
	} 	  
	/**
	 * 属性data_size的Getter方法.
	 * 创建日期:2016-08-16 17:22:11
	 * @return String
	 */
	public String getData_size () {
		return data_size;
	}   
	/**
	 * 属性data_size的Setter方法.
	 * 创建日期:2016-08-16 17:22:11
	 * @param newData_size String
	 */
	public void setData_size (String newData_size ) {
	 	this.data_size = newData_size;
	} 	  
	/**
	 * 属性doperatordate的Getter方法.
	 * 创建日期:2016-08-16 17:22:11
	 * @return UFDate
	 */
	public UFDate getDoperatordate () {
		return doperatordate;
	}   
	/**
	 * 属性doperatordate的Setter方法.
	 * 创建日期:2016-08-16 17:22:11
	 * @param newDoperatordate UFDate
	 */
	public void setDoperatordate (UFDate newDoperatordate ) {
	 	this.doperatordate = newDoperatordate;
	} 	  
	/**
	 * 属性vapprovenote的Getter方法.
	 * 创建日期:2016-08-16 17:22:11
	 * @return String
	 */
	public String getVapprovenote () {
		return vapprovenote;
	}   
	/**
	 * 属性vapprovenote的Setter方法.
	 * 创建日期:2016-08-16 17:22:11
	 * @param newVapprovenote String
	 */
	public void setVapprovenote (String newVapprovenote ) {
	 	this.vapprovenote = newVapprovenote;
	} 	  
	/**
	 * 属性vuserdef11的Getter方法.
	 * 创建日期:2016-08-16 17:22:11
	 * @return String
	 */
	public String getVuserdef11 () {
		return vuserdef11;
	}   
	/**
	 * 属性vuserdef11的Setter方法.
	 * 创建日期:2016-08-16 17:22:11
	 * @param newVuserdef11 String
	 */
	public void setVuserdef11 (String newVuserdef11 ) {
	 	this.vuserdef11 = newVuserdef11;
	} 	  
	/**
	 * 属性vuserdef12的Getter方法.
	 * 创建日期:2016-08-16 17:22:11
	 * @return String
	 */
	public String getVuserdef12 () {
		return vuserdef12;
	}   
	/**
	 * 属性vuserdef12的Setter方法.
	 * 创建日期:2016-08-16 17:22:11
	 * @param newVuserdef12 String
	 */
	public void setVuserdef12 (String newVuserdef12 ) {
	 	this.vuserdef12 = newVuserdef12;
	} 	  
	/**
	 * 属性pk_corp的Getter方法.
	 * 创建日期:2016-08-16 17:22:11
	 * @return String
	 */
	public String getPk_corp () {
		return pk_corp;
	}   
	/**
	 * 属性pk_corp的Setter方法.
	 * 创建日期:2016-08-16 17:22:11
	 * @param newPk_corp String
	 */
	public void setPk_corp (String newPk_corp ) {
	 	this.pk_corp = newPk_corp;
	} 	  
	/**
	 * 属性vuserdef13的Getter方法.
	 * 创建日期:2016-08-16 17:22:11
	 * @return String
	 */
	public String getVuserdef13 () {
		return vuserdef13;
	}   
	/**
	 * 属性vuserdef13的Setter方法.
	 * 创建日期:2016-08-16 17:22:11
	 * @param newVuserdef13 String
	 */
	public void setVuserdef13 (String newVuserdef13 ) {
	 	this.vuserdef13 = newVuserdef13;
	} 	  
	/**
	 * 属性vrevisorid的Getter方法.
	 * 创建日期:2016-08-16 17:22:11
	 * @return String
	 */
	public String getVrevisorid () {
		return vrevisorid;
	}   
	/**
	 * 属性vrevisorid的Setter方法.
	 * 创建日期:2016-08-16 17:22:11
	 * @param newVrevisorid String
	 */
	public void setVrevisorid (String newVrevisorid ) {
	 	this.vrevisorid = newVrevisorid;
	} 	  
	/**
	 * 属性vuserdef14的Getter方法.
	 * 创建日期:2016-08-16 17:22:11
	 * @return String
	 */
	public String getVuserdef14 () {
		return vuserdef14;
	}   
	/**
	 * 属性vuserdef14的Setter方法.
	 * 创建日期:2016-08-16 17:22:11
	 * @param newVuserdef14 String
	 */
	public void setVuserdef14 (String newVuserdef14 ) {
	 	this.vuserdef14 = newVuserdef14;
	} 	  
	/**
	 * 属性vbillno的Getter方法.
	 * 创建日期:2016-08-16 17:22:11
	 * @return String
	 */
	public String getVbillno () {
		return vbillno;
	}   
	/**
	 * 属性vbillno的Setter方法.
	 * 创建日期:2016-08-16 17:22:11
	 * @param newVbillno String
	 */
	public void setVbillno (String newVbillno ) {
	 	this.vbillno = newVbillno;
	} 	  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:2016-08-16 17:22:11
	 * @return Integer
	 */
	public Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:2016-08-16 17:22:11
	 * @param newDr Integer
	 */
	public void setDr (Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性vuserdef10的Getter方法.
	 * 创建日期:2016-08-16 17:22:11
	 * @return String
	 */
	public String getVuserdef10 () {
		return vuserdef10;
	}   
	/**
	 * 属性vuserdef10的Setter方法.
	 * 创建日期:2016-08-16 17:22:11
	 * @param newVuserdef10 String
	 */
	public void setVuserdef10 (String newVuserdef10 ) {
	 	this.vuserdef10 = newVuserdef10;
	} 	  
	/**
	 * 属性vuserdef7的Getter方法.
	 * 创建日期:2016-08-16 17:22:11
	 * @return String
	 */
	public String getVuserdef7 () {
		return vuserdef7;
	}   
	/**
	 * 属性vuserdef7的Setter方法.
	 * 创建日期:2016-08-16 17:22:11
	 * @param newVuserdef7 String
	 */
	public void setVuserdef7 (String newVuserdef7 ) {
	 	this.vuserdef7 = newVuserdef7;
	} 	  
	/**
	 * 属性vuserdef19的Getter方法.
	 * 创建日期:2016-08-16 17:22:11
	 * @return String
	 */
	public String getVuserdef19 () {
		return vuserdef19;
	}   
	/**
	 * 属性vuserdef19的Setter方法.
	 * 创建日期:2016-08-16 17:22:11
	 * @param newVuserdef19 String
	 */
	public void setVuserdef19 (String newVuserdef19 ) {
	 	this.vuserdef19 = newVuserdef19;
	} 	  
	/**
	 * 属性vuserdef6的Getter方法.
	 * 创建日期:2016-08-16 17:22:11
	 * @return String
	 */
	public String getVuserdef6 () {
		return vuserdef6;
	}   
	/**
	 * 属性vuserdef6的Setter方法.
	 * 创建日期:2016-08-16 17:22:11
	 * @param newVuserdef6 String
	 */
	public void setVuserdef6 (String newVuserdef6 ) {
	 	this.vuserdef6 = newVuserdef6;
	} 	  
	/**
	 * 属性vuserdef5的Getter方法.
	 * 创建日期:2016-08-16 17:22:11
	 * @return String
	 */
	public String getVuserdef5 () {
		return vuserdef5;
	}   
	/**
	 * 属性vuserdef5的Setter方法.
	 * 创建日期:2016-08-16 17:22:11
	 * @param newVuserdef5 String
	 */
	public void setVuserdef5 (String newVuserdef5 ) {
	 	this.vuserdef5 = newVuserdef5;
	} 	  
	/**
	 * 属性vuserdef4的Getter方法.
	 * 创建日期:2016-08-16 17:22:11
	 * @return String
	 */
	public String getVuserdef4 () {
		return vuserdef4;
	}   
	/**
	 * 属性vuserdef4的Setter方法.
	 * 创建日期:2016-08-16 17:22:11
	 * @param newVuserdef4 String
	 */
	public void setVuserdef4 (String newVuserdef4 ) {
	 	this.vuserdef4 = newVuserdef4;
	} 	  
	/**
	 * 属性pk_busitype的Getter方法.
	 * 创建日期:2016-08-16 17:22:11
	 * @return String
	 */
	public String getPk_busitype () {
		return pk_busitype;
	}   
	/**
	 * 属性pk_busitype的Setter方法.
	 * 创建日期:2016-08-16 17:22:11
	 * @param newPk_busitype String
	 */
	public void setPk_busitype (String newPk_busitype ) {
	 	this.pk_busitype = newPk_busitype;
	} 	  
	/**
	 * 属性vuserdef15的Getter方法.
	 * 创建日期:2016-08-16 17:22:11
	 * @return String
	 */
	public String getVuserdef15 () {
		return vuserdef15;
	}   
	/**
	 * 属性vuserdef15的Setter方法.
	 * 创建日期:2016-08-16 17:22:11
	 * @param newVuserdef15 String
	 */
	public void setVuserdef15 (String newVuserdef15 ) {
	 	this.vuserdef15 = newVuserdef15;
	} 	  
	/**
	 * 属性vuserdef16的Getter方法.
	 * 创建日期:2016-08-16 17:22:11
	 * @return String
	 */
	public String getVuserdef16 () {
		return vuserdef16;
	}   
	/**
	 * 属性vuserdef16的Setter方法.
	 * 创建日期:2016-08-16 17:22:11
	 * @param newVuserdef16 String
	 */
	public void setVuserdef16 (String newVuserdef16 ) {
	 	this.vuserdef16 = newVuserdef16;
	} 	  
	/**
	 * 属性vuserdef9的Getter方法.
	 * 创建日期:2016-08-16 17:22:11
	 * @return String
	 */
	public String getVuserdef9 () {
		return vuserdef9;
	}   
	/**
	 * 属性vuserdef9的Setter方法.
	 * 创建日期:2016-08-16 17:22:11
	 * @param newVuserdef9 String
	 */
	public void setVuserdef9 (String newVuserdef9 ) {
	 	this.vuserdef9 = newVuserdef9;
	} 	  
	/**
	 * 属性vuserdef17的Getter方法.
	 * 创建日期:2016-08-16 17:22:11
	 * @return String
	 */
	public String getVuserdef17 () {
		return vuserdef17;
	}   
	/**
	 * 属性vuserdef17的Setter方法.
	 * 创建日期:2016-08-16 17:22:11
	 * @param newVuserdef17 String
	 */
	public void setVuserdef17 (String newVuserdef17 ) {
	 	this.vuserdef17 = newVuserdef17;
	} 	  
	/**
	 * 属性vuserdef8的Getter方法.
	 * 创建日期:2016-08-16 17:22:11
	 * @return String
	 */
	public String getVuserdef8 () {
		return vuserdef8;
	}   
	/**
	 * 属性vuserdef8的Setter方法.
	 * 创建日期:2016-08-16 17:22:11
	 * @param newVuserdef8 String
	 */
	public void setVuserdef8 (String newVuserdef8 ) {
	 	this.vuserdef8 = newVuserdef8;
	} 	  
	/**
	 * 属性vuserdef18的Getter方法.
	 * 创建日期:2016-08-16 17:22:11
	 * @return String
	 */
	public String getVuserdef18 () {
		return vuserdef18;
	}   
	/**
	 * 属性vuserdef18的Setter方法.
	 * 创建日期:2016-08-16 17:22:11
	 * @param newVuserdef18 String
	 */
	public void setVuserdef18 (String newVuserdef18 ) {
	 	this.vuserdef18 = newVuserdef18;
	} 	  
	/**
	 * 属性table_name的Getter方法.
	 * 创建日期:2016-08-16 17:22:11
	 * @return String
	 */
	public String getTable_name () {
		return table_name;
	}   
	/**
	 * 属性table_name的Setter方法.
	 * 创建日期:2016-08-16 17:22:11
	 * @param newTable_name String
	 */
	public void setTable_name (String newTable_name ) {
	 	this.table_name = newTable_name;
	} 	  
	/**
	 * 属性voperatorid的Getter方法.
	 * 创建日期:2016-08-16 17:22:11
	 * @return String
	 */
	public String getVoperatorid () {
		return voperatorid;
	}   
	/**
	 * 属性voperatorid的Setter方法.
	 * 创建日期:2016-08-16 17:22:11
	 * @param newVoperatorid String
	 */
	public void setVoperatorid (String newVoperatorid ) {
	 	this.voperatorid = newVoperatorid;
	} 	  
	/**
	 * 属性pk_fbs_datafile的Getter方法.
	 * 创建日期:2016-08-16 17:22:11
	 * @return String
	 */
	public String getPk_fbs_datafile () {
		return pk_fbs_datafile;
	}   
	/**
	 * 属性pk_fbs_datafile的Setter方法.
	 * 创建日期:2016-08-16 17:22:11
	 * @param newPk_fbs_datafile String
	 */
	public void setPk_fbs_datafile (String newPk_fbs_datafile ) {
	 	this.pk_fbs_datafile = newPk_fbs_datafile;
	} 	  
	/**
	 * 属性vbillstatus的Getter方法.
	 * 创建日期:2016-08-16 17:22:11
	 * @return Integer
	 */
	public Integer getVbillstatus () {
		return vbillstatus;
	}   
	/**
	 * 属性vbillstatus的Setter方法.
	 * 创建日期:2016-08-16 17:22:11
	 * @param newVbillstatus Integer
	 */
	public void setVbillstatus (Integer newVbillstatus ) {
	 	this.vbillstatus = newVbillstatus;
	} 	  
	/**
	 * 属性pk_fbs_datafile_item的Getter方法.
	 * 创建日期:2016-08-16 17:22:11
	 * @return String
	 */
	public String getPk_fbs_datafile_item () {
		return pk_fbs_datafile_item;
	}   
	/**
	 * 属性pk_fbs_datafile_item的Setter方法.
	 * 创建日期:2016-08-16 17:22:11
	 * @param newPk_fbs_datafile_item String
	 */
	public void setPk_fbs_datafile_item (String newPk_fbs_datafile_item ) {
	 	this.pk_fbs_datafile_item = newPk_fbs_datafile_item;
	} 	  
	/**
	 * 属性vuserdef20的Getter方法.
	 * 创建日期:2016-08-16 17:22:11
	 * @return String
	 */
	public String getVuserdef20 () {
		return vuserdef20;
	}   
	/**
	 * 属性vuserdef20的Setter方法.
	 * 创建日期:2016-08-16 17:22:11
	 * @param newVuserdef20 String
	 */
	public void setVuserdef20 (String newVuserdef20 ) {
	 	this.vuserdef20 = newVuserdef20;
	} 	  
	/**
	 * 属性vnote的Getter方法.
	 * 创建日期:2016-08-16 17:22:11
	 * @return String
	 */
	public String getVnote () {
		return vnote;
	}   
	/**
	 * 属性vnote的Setter方法.
	 * 创建日期:2016-08-16 17:22:11
	 * @param newVnote String
	 */
	public void setVnote (String newVnote ) {
	 	this.vnote = newVnote;
	} 	  
	/**
	 * 属性dapprovedate的Getter方法.
	 * 创建日期:2016-08-16 17:22:11
	 * @return UFDate
	 */
	public UFDate getDapprovedate () {
		return dapprovedate;
	}   
	/**
	 * 属性dapprovedate的Setter方法.
	 * 创建日期:2016-08-16 17:22:11
	 * @param newDapprovedate UFDate
	 */
	public void setDapprovedate (UFDate newDapprovedate ) {
	 	this.dapprovedate = newDapprovedate;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2016-08-16 17:22:11
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
		return "pk_fbs_datafile";
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2016-08-16 17:22:11
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_fbs_datafile_item";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:2016-08-16 17:22:11
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "fbs_datafile_item";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2016-08-16 17:22:11
	  */
     public FbsDataFileItemVO() {
		super();	
	}    
} 
